### ISSUE TITLE
Compatibility problem with 4.2.5

### ISSUE THREAD

**Issue by stuntman999** [gobcn/ZenPacks.BCN.Ubiquiti#2]
Hi,

There is a problem with Zenoss 4.2.5, when modeling I get this error:

Problem while executing plugin ZenPacks.BCN.Ubiquiti.UbiquitiSubscriberStation
    Traceback (most recent call last): File "/opt/zenoss/Products/DataCollector/zenmodeler.py", line 647, in processClient datamaps = plugin.process(device, results, self.log) File "/opt/zenoss/ZenPacks/ZenPacks.BCN.Ubiquiti-1.02.egg/ZenPacks/BCN/Ubiquiti/modeler/plugins/ZenPacks/BCN/Ubiquiti/UbiquitiSubscriberStation.py", line 69, in process if (om.ssMAC in volatiledata) and len(volatiledata) > 0: TypeError: argument of type 'NoneType' is not iterable 

Thank you

**Comment by danfmsouza** [comment]
I'm stuck in the same. I just try to change *if (om.ssMAC in volatiledata) and len(volatiledata) > 0:* to *if (om.ssMAC in volatiledata) and len(volatiledata) is not None:*, but not solve... :(

**Comment by mjducharme** [comment]
The zenpack is certainly compatible with 4.2.5. I think something went wrong with your installation. Try reinstalling the zenpack, and if the issue persists, see if it also happens if you freshly add the device to the appropriate organizer. It might be something did not update with your existing device.

**Comment by mjducharme** [comment]
Also before installing the zenpack create the following two organizers manually:

Create an organizer "Wireless" inside /Devices/Network
Create an organizer "Ubiquiti" inside /Devices/Network/Wireless
